---
- name: Install wireguard
  apt:
    name: wireguard
    state: present

- name: Write private key
  copy:
    content: "{{ server_private_key }}"
    dest: "{{ private_key_file_path }}"
    mode: 600

- name: Write public key
  copy:
    content: "{{ server_public_key }}"
    dest: "{{ public_key_file_path }}"
    mode: 600

- name: Configure wireguard
  template:
    src: wg0.conf.j2
    dest: "{{ config_file_path }}"
    mode: 600

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
