---
- name: Converge
  hosts: all
  tasks:
    - name: "Call setup"
      setup:
    - name: "Include role"
      include_role:
        name: "wireguard"
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - testvars.yml
