name: Run molecule tests
on:
  - push

jobs:
  molecule:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest version
        uses: actions/checkout@v2
      - name: Run molecule
        uses: mawalu/molecule-action@master
